language: c
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc
    - cmake
    - libfuse-dev
    - valgrind
    - pkg-config
compiler:
- gcc
- clang
script:
- travis-ci/do-all-builds.bash
deploy:
  provider: releases
  api_key:
    secure: b2Kb1ynljx4ZEhIsVpP1iyijPXDEv4ga6AG3F/S1bRL14M/a0oysi/H6lae9UgfgLs74tCAzEbKQTiikcd9DSkVcM8re8gj1qok3xh3ICcgR4I0sD/h5wxFCRl4f67TzjobwVOFaqOyCLweJUzEtCJrK2tflR9hr2u0DIwtwKClMl+pk2yhHd36Lus65VNrjJBhYWOY91JGjH+7Ru465d2Kqgf52nBmYuyEKnxtJQPtbJoq6BRQij+vzHwcgMwNJpgIXl8v7OEAvhsOzI/3NAsaqtZnaAc2OhnZpG1sjTaD5uF3mAB6IJCzXjIDrn4i+IDUX9G7uWZwKJ2w4idQK384qPPFZFNryUMA0eHW5EiLhJB07u6Fo3udFYc6u6r5V6U/tuQ843zUWLRJOxM/KJAjS3a0q9jJnPiTY6yB5oRydOo8IWl5kisxuOKxNfUvXgq4GakAMCIyFDDcNW+hsSlWvnaNA0kaPdPiu9IQO3GMgDpwtbZwvoRPGcXGUbP9+tXu1nzI8WfYl4Q5GMciEhBl79vv/26LfkW0w0qWzS0q3iRbV6F5/N9INnmGKGNs3DlqAamEtOsVpZSUnlmOxN4L8B91bonSMd9z2mo75LPSCIORJXCtWkQxiEIkGbFp4kUJoHw21m+giIqlT4e+0B9qSncdI+5wp/ZBroFub4FA=
  file: build/BMFS-2.0.0-Linux.deb
  skip_cleanup: true
  on:
    tags: true
    repo: ReturnInfinity/BMFS
