include $(TOP)/make/config.mk

.PHONY: all
all:

.PHONY: clean
clean:

.PHONY: test
test:

.PHONY: install
install:
	mkdir -p $(DESTDIR)$(PREFIX)/include/bmfs
	cp --update *.h $(DESTDIR)$(PREFIX)/include/bmfs/

