#include <assert.h>
#include <string.h>

#include <bmfs/bmfs.h>

/* This program tests the structure size and
 * offsets generated by the compiler to make
 * sure that they can be used for reading and
 * writing from disks. */

void test_entry(void) {

	struct BMFSEntry entry;

	char buf[BMFS_ENTRY_SIZE];

	/* Make sure the structure is 64 bytes long */
	assert(sizeof(entry) == BMFS_ENTRY_SIZE);

	strcpy(entry.Name, "filename.txt");
	entry.Offset = 0x01;
	entry.Size = 0x02;
	entry.CreationTime = 0x03;
	entry.ModificationTime = 0x04;
	entry.Flags = 0x05;
	entry.UserID = 0x06;
	entry.GroupID = 0x07;

	memcpy(buf, &entry, sizeof(entry));

	/* Name */
	assert(memcmp(&buf[0], "filename.txt", sizeof("filename.txt") - 1) == 0);
	/* Size */
	assert(memcmp(&buf[192], "\x01\x00\x00\x00\x00\x00\x00\x00", 8) == 0);
	/* Offset */
	assert(memcmp(&buf[192 + 8], "\x02\x00\x00\x00\x00\x00\x00\x00", 8) == 0);
	/* Flags */
	assert(memcmp(&buf[192 + 16], "\x03\x00\x00\x00\x00\x00\x00\x00", 8) == 0);
	/* Type */
	assert(memcmp(&buf[192 + 24], "\x04", 1) == 0);
}

int main(void) {
	test_entry();
	return 0;
}

