#include <assert.h>
#include <string.h>

#include <bmfs/bmfs.h>

/* This program tests the structure size and
 * offsets generated by the compiler to make
 * sure that they can be used for reading and
 * writing from disks. */

void test_entry(void) {

	struct BMFSEntry entry;
	char buf[64];

	/* Make sure the structure is 64 bytes long */
	assert(sizeof(entry) == 64);

	strcpy(entry.FileName, "filename.txt");
	entry.FileSize = 0x01;
	entry.StartingBlock = 0x02;
	entry.ReservedBlocks = 0x03;
	entry.Type = 0x04;

	memcpy(buf, &entry, sizeof(entry));

	printf("%llx\n", *(uint64_t *)(&buf[0]));
	printf("%llx\n", *(uint64_t *)(&buf[8]));
	printf("%llx\n", *(uint64_t *)(&buf[16]));
	printf("%llx\n", *(uint64_t *)(&buf[24]));
	printf("%llx\n", *(uint64_t *)(&buf[32]));
	printf("%llx\n", *(uint64_t *)(&buf[40]));
	printf("%llx\n", *(uint64_t *)(&buf[48]));
	printf("%llx\n", *(uint64_t *)(&buf[56]));

	/* FileName */
	assert(memcmp(&buf[0], "filename.txt", sizeof("filename.txt") - 1) == 0);
	/* StartingBlock */
	assert(memcmp(&buf[32], "\x02\x00\x00\x00\x00\x00\x00\x00", 8) == 0);
	/* ReservedBlocks */
	assert(memcmp(&buf[40], "\x03\x00\x00\x00\x00\x00\x00\x00", 8) == 0);
	/* FileSize */
	assert(memcmp(&buf[48], "\x01\x00\x00\x00\x00\x00\x00\x00", 8) == 0);
	/* Type */
	assert(memcmp(&buf[56], "\x04", 1) == 0);
}

int main(void) {
	test_entry();
	return 0;
}

