name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: install packages
      run: brew install nasm x86_64-elf-gcc

    - name: build
      run: sh ./build.sh

  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: install packages
      run: sudo apt install nasm

    - name: build
      run: sh ./build.sh

  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: install packages
      run: choco install nasm x86_64-elf-gcc

    - name: build
      run: sh ./build.sh
